---
- name: Check if i386 is enabled
  ansible.builtin.command: dpkg --print-foreign-architectures
  register: foreign_arch
  changed_when: false

- name: Add i386 architecture
  become: true
  ansible.builtin.command: dpkg --add-architecture i386
  when: "'i386' not in foreign_arch.stdout"

- name: Install apt key
  become: true
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.keyname }}"
  loop: "{{ apt_keys }}"
- name: Install apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  loop: "{{ apt_repositories }}"
- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    install_recommends: true
